name: hades_simulator
dependencies:
  firebase: any
  json_annotation: any
  meta: any
dev_dependencies:
  args: any
  build_runner: any
  build_web_compilers: any
  dartsicord: ^0.1.1
  json_serializable: any
  built_template:
    path: ./built_template
dependency_overrides:
  dartsicord:
    git: https://github.com/voximity/dartsicord.git