builders:
  built_template:
    import: 'package:built_template/builder.dart'
    builder_factories:
      - createBuilder
    build_extensions:
      '.template.html':
        - '.html'
    auto_apply: dependents
    is_optional: false
    build_to: cache
    required_inputs:
      - '.js'
      - '.css'